version: "3"
services:
    my-app:
        image: webpack
        build:
            context: .
            dockerfile: Dockerfile.dev
        links:
            - postgres
            - mongo
        environment:
            DATABASE_POSTGRES_URL: postgres://postgres:newPassword@postgres:5432/packman
            DATABASE_MONGO_URL: mongodb://mongo:27017/packman
            PORT: 9001
        ports:
            - "9001:9001"
        restart: always
        volumes:
            - ./:/dist:rw
            - node_modules:/dist/node_modules
    postgres:
        container_name: postgres
        image: postgres:12
        ports:
            - "5432:5432"
        volumes:
            - ./postgresdata:/var/lib/postgresql/data
            - ./server/migrations/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: newPassword
            POSTGRES_DB: packman
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:4.18
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: secret
            PGADMIN_LISTEN_PORT: "5001"
        ports:
            - "5001:5001"
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        depends_on:
            - postgres
    mongo:
        image: mongo
        ports:
            - "27017:27017"
        restart: always
        volumes:
            - data-volume:/data/db
    mongo-express:
        image: mongo-express
        ports:
            - "8081:8081"
        restart: always
        depends_on:
            - mongo
        environment:
            - ME_CONFIG_MONGODB_PORT=27017
volumes:
    db-data:
    pgadmin-data:
    data-volume:
    node_modules:
