version: "3"
services:
    my-app:
        build:
            context: .
            dockerfile: Dockerfile
        links:
            - postgres
            - mongo
        environment:
            DATABASE_POSTGRES_URL: postgres://postgres:newPassword@postgres:5432/packman
            DATABASE_MONGO_URL: mongodb://mongo:27017/packman
            PORT: 8080
        ports:
            - "8080:8080"
        restart: always
    postgres:
        container_name: postgres
        image: postgres:12
        ports:
            - "5432:5432"
        volumes:
            - ./postgresdata:/var/lib/postgresql/data
            - ./src/backend/migrations/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: newPassword
            POSTGRES_DB: packman
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:4.18
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: secret
            PGADMIN_LISTEN_PORT: "5001"
        ports:
            - "5001:5001"
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        depends_on:
            - postgres
    mongo:
        image: mongo
        ports:
            - "27017:27017"
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongo
            MONGO_INITDB_ROOT_PASSWORD: newPassword
        volumes:
            - data-volume:/data/db
volumes:
    db-data:
    pgadmin-data:
    data-volume:
